-- =====================================================================
-- Issue #281 — Email Campaigns PHASE 2: make a real send possible and safe.
--
-- Supersedes the never-committed 20260808_phase2_unsubscribe.sql. Same two
-- core changes, plus three more that came out of reviewing the sender
-- against a real 960-recipient send.
--
-- WHAT THIS CHANGES (all additive, on tables that today hold ZERO rows):
--   1. Every campaign-recipient row gets an unguessable unsubscribe token,
--      generated by the database.
--   2. Recipient status gains 'skipped'  — a blacklisted address we chose
--      not to email, recorded rather than dropped.
--   3. Recipient status gains 'unknown'  — we called the mail provider and
--      never learned whether it went out (timeout, 5xx, unparseable
--      response). This MUST be its own status: marking those rows 'failed'
--      is what turns one "Retry failed" click into a duplicate send to
--      real families. 'unknown' is deliberately NOT retryable.
--   4. Campaign status gains 'partial'   — some sent, some did not. Today
--      a 480-sent / 480-failed campaign reports as 'sent', which is a lie
--      told to the person deciding whether to resend.
--   5. A UNIQUE index on (campaign_id, lower(email)) — makes building the
--      recipient snapshot idempotent, so re-running a half-finished
--      snapshot cannot put the same family in the list twice.
--
-- WHAT THIS DOES NOT CHANGE:
--   - No existing data is touched. Verified 2026-08-22: email_campaigns,
--     email_campaign_recipients, email_blacklist and email_templates all
--     have 0 rows. Nothing has ever been sent.
--   - No RLS change. The public unsubscribe path runs through an edge
--     function using the service role, so these tables never gain an
--     anonymous policy.
--   - No column is dropped or retyped. Every step is IF NOT EXISTS or a
--     CHECK that only widens what is allowed.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 1. Per-recipient unsubscribe token.
--    gen_random_uuid() is 122 bits of randomness — not guessable and not
--    derived from the email address, so one family's link can never be
--    used to unsubscribe another.
-- ---------------------------------------------------------------------
ALTER TABLE public.email_campaign_recipients
  ADD COLUMN IF NOT EXISTS unsubscribe_token uuid NOT NULL DEFAULT gen_random_uuid();

-- The unsubscribe endpoint looks rows up by this token on every click.
-- UNIQUE matters for more than speed: the endpoint takes the single match,
-- and a duplicate token would make a real person unable to unsubscribe.
CREATE UNIQUE INDEX IF NOT EXISTS email_campaign_recipients_unsub_token_idx
  ON public.email_campaign_recipients (unsubscribe_token);

-- ---------------------------------------------------------------------
-- 2 + 3. Widen the recipient status list.
--    Was: pending / sent / failed
--    Now: pending / sent / failed / skipped / unknown
-- ---------------------------------------------------------------------
ALTER TABLE public.email_campaign_recipients
  DROP CONSTRAINT IF EXISTS email_campaign_recipients_status_check;
ALTER TABLE public.email_campaign_recipients
  ADD CONSTRAINT email_campaign_recipients_status_check
  CHECK (status IN ('pending', 'sent', 'failed', 'skipped', 'unknown'));

-- ---------------------------------------------------------------------
-- 4. Widen the campaign status list.
--    Was: draft / sending / sent / failed
--    Now: draft / sending / sent / failed / partial
-- ---------------------------------------------------------------------
ALTER TABLE public.email_campaigns
  DROP CONSTRAINT IF EXISTS email_campaigns_status_check;
ALTER TABLE public.email_campaigns
  ADD CONSTRAINT email_campaigns_status_check
  CHECK (status IN ('draft', 'sending', 'sent', 'failed', 'partial'));

-- ---------------------------------------------------------------------
-- 5. One row per address per campaign.
--    Case-insensitive, because users.email's own UNIQUE constraint is
--    case-SENSITIVE — 74 rows currently store mixed-case addresses, so
--    a.smith@ and A.Smith@ could both exist one day and are the same
--    inbox. Verified 2026-08-22: 0 duplicate addresses exist today under
--    lower(trim(...)), so this index cannot fail to build.
-- ---------------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS email_campaign_recipients_campaign_email_idx
  ON public.email_campaign_recipients (campaign_id, lower(email));

-- ---------------------------------------------------------------------
-- 6. Index the FK the reporting screen joins on. (Advisor INFO finding.)
-- ---------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS email_campaign_recipients_user_idx
  ON public.email_campaign_recipients (user_id);

COMMIT;


-- ---------------------------------------------------------------------
-- CHECK IT WORKED — run these after, expect all five to be true.
-- ---------------------------------------------------------------------
SELECT 'token column'  AS check,
       (SELECT count(*) = 1 FROM information_schema.columns
         WHERE table_name = 'email_campaign_recipients'
           AND column_name = 'unsubscribe_token') AS ok
UNION ALL
SELECT 'recipient status allows skipped + unknown',
       (SELECT pg_get_constraintdef(oid) LIKE '%skipped%'
           AND pg_get_constraintdef(oid) LIKE '%unknown%'
          FROM pg_constraint WHERE conname = 'email_campaign_recipients_status_check')
UNION ALL
SELECT 'campaign status allows partial',
       (SELECT pg_get_constraintdef(oid) LIKE '%partial%'
          FROM pg_constraint WHERE conname = 'email_campaigns_status_check')
UNION ALL
SELECT 'one row per address per campaign',
       (SELECT count(*) = 1 FROM pg_indexes
         WHERE indexname = 'email_campaign_recipients_campaign_email_idx')
UNION ALL
SELECT 'nothing was sent while migrating',
       (SELECT count(*) = 0 FROM public.email_campaign_recipients);


-- =====================================================================
-- HOW TO UNDO — puts all five things back exactly as they were.
-- Safe to run as long as no campaign has been sent yet.
-- =====================================================================
--   DROP INDEX IF EXISTS public.email_campaign_recipients_unsub_token_idx;
--   DROP INDEX IF EXISTS public.email_campaign_recipients_campaign_email_idx;
--   DROP INDEX IF EXISTS public.email_campaign_recipients_user_idx;
--   ALTER TABLE public.email_campaign_recipients DROP COLUMN IF EXISTS unsubscribe_token;
--   ALTER TABLE public.email_campaign_recipients DROP CONSTRAINT IF EXISTS email_campaign_recipients_status_check;
--   ALTER TABLE public.email_campaign_recipients ADD CONSTRAINT email_campaign_recipients_status_check
--     CHECK (status IN ('pending', 'sent', 'failed'));
--   ALTER TABLE public.email_campaigns DROP CONSTRAINT IF EXISTS email_campaigns_status_check;
--   ALTER TABLE public.email_campaigns ADD CONSTRAINT email_campaigns_status_check
--     CHECK (status IN ('draft', 'sending', 'sent', 'failed'));


-- =====================================================================
-- DEPLOY NOTE (goes with this migration, not SQL):
--     supabase functions deploy send-campaign
--     supabase functions deploy unsubscribe --no-verify-jwt
--
--   The --no-verify-jwt on unsubscribe is REQUIRED: it is followed from a
--   link in an email by someone who is not logged in. It authenticates by
--   the token alone and uses the service role internally. send-campaign
--   stays JWT-verified and admin-only.
--
--   Deploy the functions BEFORE running this migration is fine; running
--   this migration before deploying is also fine. Neither half does
--   anything on its own — the send button is what joins them, and it
--   refuses to run if the token column is missing.
-- =====================================================================
